config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, except: %i[destroy update] do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: 0..5, numericality: { only_integer: true }
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="main">
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/_review_form.html.erb
<h3>Leave a review</h3>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul class="remove-decoration no-padding">
<% @restaurants.each do |restaurant| %>
  <li class="list-card">
    <%= link_to restaurant.name, restaurant_path(restaurant), class: "remove-decoration restaurant-link" %>: 
    |<%= restaurant.category %>|
    <%= restaurant.phone_number %> - 
    <%= restaurant.address %>
  </li>
<% end %>
</ul>
<%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, as: :select, collection: %w[chinese italian japanese french belgian]%>
  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>
<%= link_to "Return to list",  restaurants_path, class: "btn btn-secondary" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.category %></h3>
<h4><%= @restaurant.phone_number %></h4>
<h4><%= @restaurant.address %></h4>
<br>
<h2>Reviews</h2>
<ol>
  <% @restaurant.reviews.each do |review| %>
  <li>
    <%= review.content %> 
    Rating: <%= review.rating %>
  </li>
  <% end %>
</ol>
<br>
<%= render "review_form", { restaurant: @restaurant, review: @review } %>
<%= link_to "Back", restaurants_path, class: "btn btn-secondary" %>

app/views/reviews/new.html.erb
<h1>Leave a review</h1>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
<%= link_to "Back", restaurant_path(@restaurant), class: "btn btn-secondary" %>